name: Deploy Portfolio

on:
  push:
    branches: [feature]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Replace placeholders
        run: |
          sed -i "s|__EMAILJS_KEY__|${{ secrets.EMAILJS_KEY }}|g" script.js
          sed -i "s|__SERVICE_ID__|${{ secrets.EMAILJS_SERVICE }}|g" script.js
          sed -i "s|__TEMPLATE_ID__|${{ secrets.EMAILJS_TEMPLATE }}|g" script.js

      - name: Deploy
        run: echo deploy here